name       : kscreenlocker
version    : 5.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/kscreenlocker-5.12.0.tar.xz : 5c6002ba33e2337cfc05076bbaf58416a6f7f0a88663ccd806262e6fbb365383
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake -DHAVE_PAM=YES .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/kde $installdir/etc/pam.d/kde
