name       : kscreenlocker
version    : 5.11.3
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.3/kscreenlocker-5.11.3.tar.xz : 5ba019d5d002511ec09deb941af1c38b1373b7eac418853f98badbffa7621d44
license    : GPL-2.0
component  : desktop.kde.core
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake -DHAVE_PAM=YES .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/kde $installdir/etc/pam.d/kde
