name       : kscreenlocker
version    : 5.17.3
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.3/kscreenlocker-5.17.3.tar.xz : d74efdeb4166162b4d0df994fee97ae1ef4201931ca56eecca487ab11acda2ef
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kidletime-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake_ninja -DHAVE_PAM=YES \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
