name       : kscreenlocker
version    : 5.11.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/kscreenlocker-5.11.4.tar.xz : 87e049ea0771a72e2919fb618348c58f56b476d520f57ce7c269e877341a4464
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake -DHAVE_PAM=YES .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/kde $installdir/etc/pam.d/kde
