name       : kscreenlocker
version    : 5.23.2
release    : 75
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.2/kscreenlocker-5.23.2.tar.xz : e609dcdbf8191fea98facd9659b3681061f46b7d0bfc3b0a545eed7f5e91d8f9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
optimize   : lto
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - layer-shell-qt-devel
    - solid-devel
setup      : |
    %cmake_ninja -DHAVE_PAM=YES \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
    %qml_cache
