name       : kscreenlocker
version    : 5.21.3
release    : 66
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.3/kscreenlocker-5.21.3.tar.xz : 0012c4f0394bc6cd522a8fc4ed78f02e641b55d1baf8a81f6fd926c538bf54c2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
optimize   : lto
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - kpackage-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake_ninja -DHAVE_PAM=YES \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
    %qml_cache
