name       : kscreenlocker
version    : 5.20.4
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/kscreenlocker-5.20.4.tar.xz : d80d4625a0a48a7a63c5ff8255e8639eb2fb57ebc436c46979949b39fc530126
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - ki18n-devel
    - kidletime-devel
    - knotifications-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake_ninja -DHAVE_PAM=YES \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
    %qml_cache
