name       : kscreenlocker
version    : 5.15.5
release    : 35
source     :
    - https://download.kde.org/stable/plasma/5.15.5/kscreenlocker-5.15.5.tar.xz : 09d9d63e81a60d1c95532639287ba29403e0b04d7e4d46f5a49adbfccf215dcd
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - extra-cmake-modules
    - kcmutils-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdeclarative-devel
    - kglobalaccel-devel
    - kidletime-devel
    - knotifications-devel
    - ktextwidgets-devel
    - kwayland-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - pam-devel
    - solid-devel
setup      : |
    %cmake_ninja -DHAVE_PAM=YES \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
